debug: true
all_data: true  # use pseudo data
ds_path: 'data/processed'
verbose: 1
device: GPU
model_name: 'ECA_NFNetL0'
pretrain: imagenet
seed: 42
clean_data: true # clean the data
folds: 5
selected_folds:
- 0
- 1
- 2
- 3
- 4
img_size:
- 360
- 640
resize_with_pad: false
batch_size: 32
infer_bs_scale: 2.0
epochs: 25
save_after: 8 # save model after certain epochs
loss: Huber # BCE, Huber, MAE
huber_delta: 1.0 # for huber loss
optimizer: Adam # AdamW, RectifiedAdam, Adam, Adagrad, SGD, Yogi
augment: true
transform_prob: 0.5
fill_mode: constant # constant, reflect, nearest
rot: 2.0 # proprtional
shr: 2.0 # proprtional
hzoom: 100.0 # inv proportional
vzoom: 100.0 # inv proportional
hshift: 5.0  # proportional
vshift: 5.0  # proportional
distortion_prob: 0.5 # optical & grid distortion probability
hflip: false # horizontal flip
vflip: false # vertical flip
clip: false
lr: 0.001 # base_lr
lr_max: 1.25e-6 # max lr - will be multiplied by batch_size
lr_min: 1.0e-6 # min lr
lr_ramp_ep: 5 # warming up epochs
lr_sus_ep: 0 # sustain epochs lr after warming up
lr_decay: 0.8 # decay rate
scheduler: exp #cosine, exp, step
remove_border: true # remove border of the image
fill_border: false  # fill removed border with 0 value
remove_symbol: true # remove bottom-left symbol
border_prob: 0.0    # randomly fill border with 0 value
drop_prob: 0.75
drop_cnt: 12
drop_size: 0.05
sat:
- 0.7
- 1.3
cont:
- 0.8
- 1.2
bri: 0.15
hue: 0.05
gray_prob: 0.25 # randomly convert image to grayscale
tta: 1 # test time augmentation
num_features: 128 # number of features after global average pooling
zero_distance: false # add zero distance or not
rounding: true  # round the output to closest distance
agg: median # aggregation function to merge prediction
target_col:
- distance
tab_cols:
- video_id
- time
- x1
- y1
- x2
- y2
- probability
- park
- site_id

ensemble_idx : [9, 6, 10, 7, 1, 3, 10, 0, 9, 5, 1, 10]
ensemble_weights : [0.43, 0.34, 0.18, 0.125, 0.085, 0.07, 0.04, 0.04, 0.025, 0.02, 0.025]